### ISSUE TITLE
Do you think that I can use it to group some custom widgets together?

### ISSUE THREAD

**Issue by moebiussurfing** [tettou771/ofxComponentUI#1]
Hey @tettou771 , 
thanks for sharing.

Sorry for asking without looking more deeper first,
but do you think the add-on could be used to group some custom widgets that I have?

I am using some custom widgets, they are draggable by using the mouse, 
and size can be changed with mouse wheel too.
Also I have a kind of draggable ofRectangle to draw some plotting inside:

![image](https://user-images.githubusercontent.com/2106149/189507501-d96a13ab-e17b-4cd8-8855-30d284e85f0e.png)

The thing is that I would like to group all them to move them linked together,
(and maybe to do some basic responsive layout with them to follow the window resizing ...)

Do you think that I can use this add-on for this purpose?
Any tip around the topic?

Thanks!

**Comment by tettou771** [comment]
Thank you for asking!
What are you making? It looks like synthesizer or oscilloscope and look awesome!

I think my addons (ofxComponent, ofxComponentUI) makes widget grouping easily!
But, the architecture is strange (original, but inspired by Unity and JUCE).
For that reason, maybe it needs many changes your project.

I use ofxComponent every time and I think useful. On the other hand, I unconfident it is mutch for everybody.

I was write no information of this addon. sorry for begin lazy.
I wrote README.md, and add some comment in example.
But, much of the complexity is due of ofxComponent.
I wrote little more information in ofxComponent/README.md.
I'm glad if it helps you.

Tips of addon

If you use this, your custom component should be make as derived class of ofxComponentBase, and instantiate as shared_ptr<T>.

ofxComponentBase has convenient methods for override.
For ex, onStart, onUpdate, onDraw, onKeyPressed, ...and more.
And, it has getter of local position of mouse, getMouseX(), getMousePos(), and more.
These methods use globalToLocalPos(). ofxComponentBase has localMatrix that used in draw.

Window and View is defined of ofxComponentUI, and derived class of ofxComponentBase. I recommend test first ofxComponent.

**Comment by moebiussurfing** [comment]
Thanks for your reply!

Cool. It seems that then could be used to do this job.

~~I am now testing, but I am being a bit lost on the local/global coordinates, but I'll get it.
(When I draw my widgets, they're not coincident with the component container. 
Probably I must add/translate the widget position and the global position...)~~

EDIT: 
Got it working. Thanks
![image](https://user-images.githubusercontent.com/2106149/190309200-bba2d9cc-4736-4bd3-a9ff-d1bab49817b5.png)

--

PS:
About the layouting part, there's an interesting add-on that looks useful for that:
https://github.com/bakercp/ofxDOM 
It has been used by [ofxGuiExtended ](https://github.com/frauzufall/ofxGuiExtended) and [ofxLineaDeTiempo ](https://github.com/roymacdonald/ofxLineaDeTiempo) (in combination with [ofxMUI](https://github.com/bakercp/ofxMUI) too.)
It looks interesting but there's no good examples, and has been too hard to learn it in my case.

**Comment by moebiussurfing** [comment]
> What are you making? It looks like synthesizer or oscilloscope and look awesome!

Thanks. It's a WIP audio analyzer add-on/module. 
To get an audio input, smooth the signal and to get some bang triggers.
It's mainly based on https://github.com/moebiussurfing/ofxSurfingSmooth.

![image](https://user-images.githubusercontent.com/2106149/190039969-ff21bb0d-eebf-4dd9-9452-3a8a7a525e02.png)
