### ISSUE TITLE
ClickableComponent.h not in repository

### ISSUE THREAD

**Issue by veketor** [tettou771/ofxComponentUI#2]
Hi tettou771,  the file ClickableComponent.h is not uploaded to the repo.

Thanks.

**Comment by tettou771** [comment]
Hi veketor!

> the file ClickableComponent.h is not uploaded to the repo.

It is true that I forgot to add that file, but I deleted it in the latest version because it was no longer needed in the process of making it.

Compile errors are a problem, so I'll fix them in a few days.  I'm sorry I can't work right now because I'm on a business trip.

The reason I wanted to create ClickableComponent is that I wanted to define an event that occurs only on the top component when clicked, but I want to solve that by creating a method ofxComponentBase::isTopComponent() .  I just want to be able to check whether it is the component that is being touched by the mouse and is on the top layer.

(I wrote with Google translation)

**Comment by veketor** [comment]
Hi again tettou771!
Thanks for your quick response.
If the file is not needed for you and deleted the file, dont waste your time rewriting the ClickableComponent.h,  I´ll be loocking this repository for future news.

Your ofxComponent is awesome.
Thanks again,
veketor

**Comment by tettou771** [comment]
Hello veketor! 
Apologies for the wait. I've finally managed to make it work without errors when combined with the latest version of ofxComponent. There was an issue where onMousePressed() would be handled simultaneously when background objects overlapped during a mouse click, but this can now be avoided with the following methods. All of these are implemented as methods of the ofxComponentBase class. Below is a quote from the ofxComponentBase.h file. Please also check the updated ofxComponent/example.

```cpp
// This method is called when the mouse is pressed down while over the topmost visible component, even if multiple components are overlapping.
// It handles the actions or events that should occur in response to the mouse press on that topmost component.
// This ensures that only the foremost layer receives the event, making it particularly useful for triggering events, such as button clicks or starting a drag action, when interacting with overlapping UI components.
virtual void onMousePressedOverComponent(ofMouseEventArgs&){}

// is mouse pointer on this
// When using this for creating UI elements, there may be issues with multiple overlapping buttons.
// Consider using isMouseOver() as well.
bool isMouseInside();

// isMouseOver() returns true when the mouse pointer is hovering over an object and the object is located on the top layer.
// When implementing UI elements such as buttons, if multiple buttons overlap, using isMouseInside() alone may cause multiple objects to respond.
// To prevent this, by also checking whether the object is on the top layer, simultaneous pressing of overlapping buttons can be avoided.
// In addition, when implementing buttons, another option is to register events with mousePressedTopEvents.
bool isMouseOver();

// This method returns true while the mouse is clicked and held over the component.
// It continues to return true even if the mouse is dragged outside of the component.
// This behavior is useful for recognizing mouse movements when dragging a component, even when outside of its bounds.
bool isMousePressedOverComponent();
```
